7 Steps of the machine learning process

1- data collection
2- data processing and preparation
3- feature engineering
4- model selection
5- model training and data pipeline
6- model validation
7- model persistance


1- Numpy

NumPy arrays are basically just Python lists with added features.

In [3]:
import numpy as np

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


The dtype keyword argument takes in a NumPy type and manually casts the array to the specified type.


In [4]:
#Array vs. list

# List way
list_a = [1, 2, 3, 4]
list_b = [10, 20, 30, 40]
result = [x * y for x, y in zip(list_a, list_b)]
print(result)

# NumPy way
import numpy as np
array_a = np.array([1, 2, 3, 4])
array_b = np.array([10, 20, 30, 40])
result = array_a * array_b
print(result)

[10, 40, 90, 160]
[ 10  40  90 160]


In [3]:
import numpy as np
zeros = np.zeros((3, 2))
print(zeros)
ones = np.ones((4, 5))
print(ones)
arr1 = np.arange(15)
print(arr1)
arr2 = np.arange(5, 20, 4)
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  9 13 17]


In [4]:
linespace_arr = np.linspace(0, 1, 5)
print(linespace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
random_arr = np.random.rand(3, 4)
print(random_arr)

[[0.01132975 0.31746288 0.67377601 0.26293587]
 [0.44046189 0.88872837 0.05497566 0.90476883]
 [0.14673528 0.49554522 0.29814235 0.00206985]]


In [11]:
random_integers = np.random.randint(0, 10, size=(2, 2))
print(random_integers)


#Library,A collection of related code.,numpy
#Module,A single file or sub-component.,random
#Function,A block of code that performs a specific action.,randint()

[[7 2]
 [1 5]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-1])            
print(arr[-2])            
print(arr[len(arr)//2])   
print(arr[:])          
print(arr[::2])        
print(arr[::3])        

7
6
4
[1 2 3 4 5 6 7]
[1 3 5 7]
[1 4 7]


In [17]:
#2D Array Indexing and Slicing Practice

matrix = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
matrix.shape



(3, 4)

In [23]:
matrix[:,0:2]

array([[ 10,  20],
       [ 50,  60],
       [ 90, 100]])

In [25]:
import numpy as np

arr_1x3 = np.array([1, 2, 3])

arr_3x3 = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
result = arr_1x3 * arr_3x3
print(result)

total_sum = result.sum()
minimum = result.min()
maximum = result.max()
average = result.mean()

print(total_sum, minimum, maximum, average)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
96 1 27 10.666666666666666
